version: "3.9"

services:
  app:
    container_name: django-essential
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
