# Generated by Django 4.1.4 on 2023-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('graph_app', '0002_auto_20210303_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='groups',
            field=models.ManyToManyField(related_name='api_clients', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='user_permissions',
            field=models.ManyToManyField(related_name='api_clients', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
